[[plugins]]
repo = 'junegunn/fzf'
build_on = '''
./install -all
'''

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'markonm/traces.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'


[[plugins]]
repo = 'tpope/vim-surround'


[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
# ヘルプの日本語化
repo = 'vim-jp/vimdoc-ja'

