[[plugins]]
# ファジー検索
repo = 'junegunn/fzf'
build = './install --bin'
merged = 0

[[plugins]]
# ファジー検索
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
  command! -bang -nargs=* Rg
    \ call fzf#vim#grep(
    \   'rg --line-number --no-heading '.shellescape(<q-args>), 0,
    \   fzf#vim#with_preview({'options': '--exact --reverse'}, 'right:50%:wrap'))
'''

[[plugins]]
# 正規表現をプレビュー
repo = 'markonm/traces.vim'

[[plugins]]
# 括弧やクォーテーションへの操作を拡張
repo = 'machakann/vim-sandwich'

[[plugins]]
# コメントアウトプラグイン
repo = 'tpope/vim-commentary'

[[plugins]]
# ヘルプの日本語化
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
# yankする部分をハイライト
repo = 'machakann/vim-highlightedyank'

[[plugins]]
# language server
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = 0
build = './install.sh nightly'
hook_add = 'source ~/.config/nvim/coc-settings.json'

[[plugins]]
# CocListを強化
repo = 'neoclide/coc-lists'

[[plugins]]
# 括弧の自動補完
repo = 'jiangmiao/auto-pairs'

[[plugins]]
# vimからgitの操作を可能にする
repo = 'tpope/vim-fugitive'

[[plugins]]
# vimからlazygitの操作を可能にする
repo = 'kdheepak/lazygit.nvim'

[[plugins]]
# Gitの情報をコードの横に表示
repo = 'airblade/vim-gitgutter'

[[plugins]]
# スニッペットプラグイン
repo = 'honza/vim-snippets'

[[plugins]]
# シンタックスハイライトを拡張
repo = 'nvim-treesitter/nvim-treesitter'

[[plugins]]
# ターミナルの切り替えをスムーズにする
# repo = 'caenrique/nvim-toggle-terminal'
repo = 'akinsho/toggleterm.nvim'

[[plugins]]
# コーディングの記録をつける
repo = 'wakatime/vim-wakatime'

# ((((((((((((((( 言語に関するプラグイン )))))))))))))))
[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'vim-scripts/DoxygenToolkit.vim'

################# 見た目系のプラグイン #################

[[plugins]]
# ステータスバーのプラグイン
repo = 'vim-airline/vim-airline'

[[plugins]]
# ステータスバーのプラグインのテーマ拡張
repo = 'vim-airline/vim-airline-themes'

# ------------ カラースキーマのプラグイン ------------ #
[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'arcticicestudio/nord-vim'

[[plugins]]
repo = 'ulwlu/elly.vim'

[[plugins]]
repo = 'jdkanani/vim-material-theme'

[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'sainnhe/gruvbox-material'
