[[plugins]]
repo = 'junegunn/fzf'

[[plugins]]
repo = 'markonm/traces.vim'

[[plugins]]
repo = 'lambdalisue/gina.vim'

[[plugins]]
repo = 'machakann/vim-sandwich'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
# ヘルプの日本語化
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
# yankする部分をハイライト
repo = 'machakann/vim-highlightedyank'

[[plugins]]
# language server
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = 0
# hook_source = 'call coil398#init#coc#hook_source()'


[[plugins]]
# 括弧の自動補完
repo = 'jiangmiao/auto-pairs'

[[plugins]]
# ステータスバーのプラグイン
repo = 'vim-airline/vim-airline'

[[plugins]]
# ステータスバーのプラグインのテーマ拡張
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
# カラースキーマのプラグイン
repo = 'tomasr/molokai'

[[plugins]]
# カラースキーマのプラグイン
repo = 'arcticicestudio/nord-vim'

[[plugins]]
# カラースキーマのプラグイン
repo = 'ulwlu/elly.vim'

[[plugins]]
# カラースキーマのプラグイン
repo = 'jdkanani/vim-material-theme'

[[plugins]]
# カラースキーマのプラグイン
repo = 'jacoborus/tender.vim'
